---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/replication/.aar_doc.yml
      - roles/replication/README.md
      - roles/replication/meta/argument_specs.yml
      - roles/replication/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.dfs'
jobs:
  docs_replication:
    name: Generate replication role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.dfs'
      role_name: 'replication'
