---
name: Molecule - replication role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/replication/**
      - '!roles/replication/.aar_doc.yml'
      - '!roles/replication/README.md'
      - '!roles/replication/meta/argument_specs.yml'
      - '!roles/replication/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/replication/**
      - '!roles/replication/.aar_doc.yml'
      - '!roles/replication/README.md'
      - '!roles/replication/meta/argument_specs.yml'
      - '!roles/replication/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.dfs'
jobs:
  molecule:
    name: Run Molecule tests
    uses: trippsoft/github-actions/.github/workflows/molecule.yml@main
    with:
      working_directory: 'trippsc2.dfs'
      role_name: 'replication'
      box: ${{ matrix.box }}
    strategy:
      fail-fast: false
      matrix:
        box:
          - w2025_cis
          - w2022_cis
          - w2019_cis
